name: Mark stale issues and pull requests
on:
  schedule:
    - cron:  '40 6 * * *'
  workflow_dispatch:

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: linuxserver/github-workflows/.github/workflows/issues-cron.yml@v1
    secrets: inherit
